run:
  timeout: 15m
  tests: true

linters:
  enable:
    - deadcode
    - funlen
    - gas
    - revive
    - ineffassign
    - megacheck
    - staticcheck
    - errcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - misspell

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - staticcheck
        - unused
        - varcheck
    - path: doc.go
      linters:
        - goheader

linters-settings:
  goheader:
    template: |-
        Use of this source code is governed by a BSD-style
        license that can be found in the LICENSE file.
